//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalView
    {
        public int AnimalID { get; set; }
        public string Classis { get; set; }
        public string Species { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<double> Weight { get; set; }
    }
}
