//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int AnimalID { get; set; }
        public int Classis { get; set; }
        public int Species { get; set; }
        public byte Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Classis Classis1 { get; set; }
        public virtual Sex Sex1 { get; set; }
        public virtual Species Species1 { get; set; }
    }
}
