//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetShopDatabaseEntities : DbContext
    {
        public PetShopDatabaseEntities()
            : base("name=PetShopDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Classis> Classis { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<AnimalView> AnimalView { get; set; }
    }
}
